### ISSUE TITLE
Sleep command too long in Infrastructure Scaling fast script

### ISSUE THREAD

**Issue by seanson** [GoogleCloudPlatform/anthos-service-mesh-workshop#48]
The sleep command in `fasttrack_scripts/infrastructure-scaling.sh` sleeps for 5 hours instead of 5 minutes.

**Comment by cloud-pharaoh** [comment]
Thanks for catching that Sean!

**Comment by cloud-pharaoh** [comment]
Please sign the CLA so I can merge the fix.
