### ISSUE TITLE
Rebuild of Mesh Workshop in my own envrionment.

### ISSUE THREAD

**Issue by ericwhiteau** [GoogleCloudPlatform/anthos-service-mesh-workshop#53]
Thanks very much for the workshop in Sydney.

I have rebuilt the environment in our GCP environment in I have two things to highlight.
Not really issues but they do stop the build so worth a mention.

The script for setup of admin  in bootstrap  fails with a '.'  in the constructed project name  with "eric.wh"  (shortend to 4 characters.  workshop accounts were user000 so no . )
setup-terraform-admin-project.sh  Line 74
ORG_USER=${ORG_USER:0:7}

Second.
I had to give billing user writes to the build service account.  as the User creates the first project, but terraform creates the other projects.  (not sure if I missed this somewhere, but I couldn't see it)

Cheers.    All built successfully after these two.

thanks.

**Comment by cloud-pharaoh** [comment]
Thanks Eric. We will address the issue with the '.' in the script.

As for the second item, that should have been taken care of in the script:
Line 135 in setup-terraform-admin-project.sh
`echo -e "\n${CYAN}Giving cloudbuild service account billing user IAM role at the Org level...${NC}"
gcloud organizations add-iam-policy-binding ${TF_VAR_org_id} \
--member serviceAccount:${TF_CLOUDBUILD_SA} \
--role roles/billing.user`
